name: "android_github_action_flow"

on:
    push:
        branches:
            - master


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checking out repo code
          uses: actions/checkout@v2  
        
        - name: Install java 17
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'temurin'

        - name : Install flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.24.5'
            cache: true
        
        - name : Install dependencies
          run: flutter pub get
        
        - name: regenerate files
          run: dart run build_runner build --delete-conflicting-outputs 

        - name: Setup ruby
          uses: ruby/setup-ruby@v1
          with:
            ruby-version: '3.3.6'   
            bundler-cache: true
            working-directory: android 
                

        - name: Get commit message
          id: commit_message
          run: |
            echo "MESSAGE<<EOF" >> $GITHUB_ENV
            git log -1 --pretty=%B >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV

        - name: Skip workflow if not a release
            if: "!contains(env.MESSAGE, 'apk release')"
            run: echo "Skipping workflow as commit message does not contain 'apk release'." && exit 0
  
        
          

        - name: Build app and distribute
          env:
            FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
          run: |
            cd android && bundle exec fastlane khaled   
                                    